[package]
id = "linux-x11-anim-demo"
name = "Linux X11 Anim Demo"
version = "0.1.0"
source = "apps/linux_x11_anim_demo"
output = "packages/lx11anim.rpx"

[app]
entry = "main.rdx"
layout = "main.rml"

[[files]]
src = "LX11ANIM.BIN"
dst = "LX11ANIM.BIN"

[[files]]
src = "LD.BIN"
dst = "LD.BIN"

[sign]
enabled = true
output = "packages/lx11anim.rpx.sig"
