[package]
id = "hello-redux"
name = "Hello Redux"
version = "0.1.0"
source = "apps/hello_redux"
output = "packages/hello_redux.rpx"

[app]
entry = "main.rdx"
layout = "main.rml"

[[files]]
src = "main.rml"
dst = "main.rml"

[[files]]
src = "main.rdx"
dst = "main.rdx"

[[files]]
src = "manifest.json"
dst = "manifest.json"

[sign]
enabled = true
output = "packages/hello_redux.rpx.sig"
