[package]
id = "linux-sandbox-smoke"
name = "Linux Sandbox Smoke"
version = "0.1.0"
source = "apps/linux_sandbox_smoke"
output = "packages/lsbx.rpx"

[app]
entry = "main.rdx"
layout = "main.rml"

[[files]]
src = "chrome-sandbox"
dst = "chrome-sandbox"

[sign]
enabled = true
output = "packages/lsbx.rpx.sig"
